spring:
  application:
    name: zuul-server
  zipkin:
    base-url: http://localhost:8020
server:
  port: 8002
zuul:
  routes:
    auth:
      path: /auth/**
      sensitiveHeaders:
      serviceId: oauth-server
    static:
      path: /static/**
      sensitiveHeaders:
      serviceId: static-resource
    user:
      path: /user/**
      sensitiveHeaders:
      serviceId: user-server
    hotel:
      path: /hotel/**
      sensitiveHeaders:
      serviceId: hotel-server
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8002/auth/users/user
      prefer-token-info: false
    client:
      access-token-uri: http://localhost:8002/auth/oauth/token
      user-authorization-uri: http://localhost:8002/auth/oauth/authorize
      client-id: webapp
#access-token-uri:表示请求token的地址
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8001}/eureka/

#负载均衡配置
ribbon:        #饥饿加载
  eager-load:
      enabled: true
  ReadTimeout: 3000000
  ConnectTimeout: 3000000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1
  eureka:
    enabled: true
#eureka客户端ribbon刷新时间
  ServerListRefreshInterval: 5000000

#链路熔断配置
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 6000000