spring:
  application:
    name: hotel-server
  zipkin:
    base-url: http://localhost:8020
#  mvc:
#    static-path-pattern: /resources/**
#  resources:
#    static-locations: classpath:/META-INF/resources/,classpath:/resources/, classpath:/static/, classpath:/public/,file:${web.upload-path}

server:
  port: 8007

mybatis:
  typeAliasesPackage: cn.lyf.hotelserver.entity
  mapperLocations: classpath*:mapper/*.xml

management:
  security:
    enabled: false

feign.hystirx.enable: true

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8002/auth/users/user
      prefer-token-info: false