spring:
  application:
    name: user-server
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3309/db_hotel?useSSL=false
#    username: root
#    password: 123456
#  zipkin:
#    base-url: http://localhost:8020

mybatis:
  type-aliases-package: cn.lyf.userserver.entity
  mapper-locations: classpath:mapper/**/*.xml
#eureka:
#  client:
#    service-url:
#      defaultZone: http://${eureka.host:localhost}:${eureka.port:8001}/eureka/
server:
  port: 8005
#security:
#  oauth2:
#    resource:
#
security:
  oauth2:
    resource:
      filter-order: 3
      user-info-uri: http://localhost:8002/auth/users/user      #内置有user对象的地址，才能获取到同一个token
      prefer-token-info: false