server:
  port: 8011
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sweetfly123/configserver.git
          search-paths: config
          default-label: master
          username: 991370140@qq.com
          password: liuyunfeng123
    bus:
      trace:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
management:
  security:
    enabled: false
