spring:
  application:
    name: oauth-server
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3309/db_hotel?useSSL=false
#    username: root
#    password: 123456
#  zipkin:
#    base-url: http://localhost:8020
server:
  port: 8003
#eureka:
#  client:
#    service-url:
#      defaultZone: http://${eureka.host:localhost}:${eureka.port:8001}/eureka/
mybatis:
  type-aliases-package: cn.lyf.oauthserver.entity
  mapper-locations: classpath:mapper/**/*.xml

security:
  oauth2:
    resource:
      filter-order: 3